go_import_path: github.com/webdeskltd/dadata
language: go
sudo: false

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"

env:
  - GO111MODULE=on

branches:
  only:
  - v2
  - master
  - issue-1

before_script:
  - go get -v ./...

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - go test -v ./...