go_import_path: github.com/webdeskltd/dadata
language: go
sudo: false

matrix:
  include:
    - go: "1.10.x"
      script:  go test -v ./...

    - go: "1.11.x"
      script: go test -v -mod=vendor ./...

#  - "1.7.x"
#  - "1.8.x"
#  - "1.9.x"
  - "1.10.x"
#  - "1.11.x"
#  - master

env:
  - GO111MODULE=on

install: false

branches:
  only:
  - v2
  - master
  - 2

#notifications:
#  email:
#    on_success: change
#    on_failure: always

#script:
#  - go get -t -v ./...
#  - go install ./...
#  - go test -v ./...
